---
- name: install docker repo key
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present

- name: install docker repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
    state: present

- name: install docker and deps
  apt:
    name: docker-ce=17.06.2~ce-0~ubuntu
    update_cache: yes
    state: present

# - service:
#    name: docker
#    state: restarted

# docker_container cannot find installed docker-py
# https://github.com/ansible/ansible-modules-core/issues/4246
- name: 'Install pip'
  apt:
    name: python-pip
    state: present

- name: 'Install docker-py'
  pip:
    name: docker-py
    state: present
