---
- name: install docker repo key
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present

- name: install docker repo
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present

- name: install docker and deps
  apt: name=docker-engine update_cache=yes

- service: name=docker state=restarted
